# Site settings
title: Example Site
email: your-email@domain.com
tagline: Site Tagline
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: twitter-username
facebook_username: facebook-username
github_username:  github-username

# Build settings
markdown: kramdown

######################################## Custom
highlighter: pygments
encoding: utf-8

# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: ["README.md"]
